# Generated by Django 4.2.1 on 2023-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True)),
                ('email', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('avatar', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
