# Generated by Django 4.2.1 on 2023-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='writer',
            name='descripcion_general',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='titulo',
            field=models.CharField(default='no_data', max_length=254),
        ),
        migrations.AlterField(
            model_name='writer',
            name='descripcion',
            field=models.CharField(max_length=254),
        ),
    ]
