# Generated by Django 4.2.1 on 2023-05-25 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('texto', models.CharField(max_length=254)),
                ('categoria', models.CharField(max_length=254)),
                ('extra', models.CharField(blank=True)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 24, 21, 30, 9, 264771))),
                ('url', models.CharField(max_length=254)),
                ('is_publish', models.BooleanField(default=True)),
                ('imagen_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('imagen_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('imagen_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('imagen_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='writers.writer')),
            ],
        ),
    ]
