# Generated by Django 4.2.1 on 2023-05-27 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='extra',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 27, 14, 1, 3, 453746)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='texto',
            field=models.CharField(blank=True),
        ),
    ]
